from enum import Enum
from typing import Dict, List

from pydantic import BaseModel, Field


class ChessPuzzleItem(BaseModel):
    """
    Represents a specific chess puzzle instance and its ground-truth metadata.

    Attributes:
        uuid (str): Unique identifier for the puzzle.
        prompt (List[Dict[str, str]]): tokenizer compatible dicts (e.g., [{'role': 'user', 'content': '...'}]).
        best_move (str): The ground-truth winning move represented in UCI format.
        rating (int): The difficulty level of the puzzle, expressed as an Elo rating.
        fen (str): Forsyth-Edwards Notation string representing the board state before the move.
        tags (List[str]): Categorical labels describing tactical themes present in the puzzle.
    """

    uuid: str = Field(description="Unique UUID per item")

    prompt: List[Dict[str, str]] = Field(
        default_factory=list,
        description="list of tokenizer compatible message dictionaries (e.g., [{'role': 'user', 'content': '...'}]).",
    )

    best_move: str = Field(description="The UCI string of the winning move.")

    rating: int = Field(description="The Elo rating of the puzzle.")

    fen: str = Field(description="The FEN position before the best move.")

    tags: List[str] = Field(
        default_factory=list, description="List of tactical themes (e.g., 'fork')."
    )


class MoveExtractionError(Enum):
    """
    Enumerates the specific failure modes encountered during model response parsing.

    Attributes:
        MISSING_TAGS: The response structure lacked the required XML tags.
        UNPARSABLE_MOVE: The text within <answer> tags is not a valid SAN (e.g., Nf3) or UCI (e.g., g1f3) string.

        ILLEGAL_MOVE: The move string is syntactically valid but impossible in the current FEN.
    """

    MISSING_TAGS = "missing_tags"

    UNPARSABLE_MOVE = "unparsable_move"

    ILLEGAL_MOVE = "illegal_move"


class RolloutItem(BaseModel):
    """
    Encapsulates a model's generation attempt, including input context and technical artifacts.

    Attributes:
        input_item (ChessPuzzleItem): The original input item that generated this rollout.
        model_completion (Dict[str, str]): tokenizer compatible dicts (e.g., {'role': 'assistant', 'content': '...'} ).
        tokens (List[int]): The sequence of numerical token IDs produced by the model.
        masks (List[bool]): Logical flags identifying tokens used for loss computation or masking.
        logprobs (List[float]): The log-probability values for each generated token.
    """

    input_item: ChessPuzzleItem = Field(
        ..., description="The original input item that generated this rollout."
    )

    model_completion: Dict[str, str] = Field(
        ...,
        description="The model completion as a message dictionary (e.g., {'role': 'assistant', 'content': '...'} ).",
    )

    tokens: List[int] = Field(
        ..., description="The sequence of token IDs generated by the model."
    )

    masks: List[int] = Field(
        ...,
        description="Tokens with -100 for prompt positions, actual IDs for completion.",
    )

    logprobs: List[float] = Field(
        ...,
        description="The log probabilities for each token in the generated sequence.",
    )
