env:
  group_size: 8
  max_num_workers: 32
  max_eval_workers: 16
  max_num_workers_per_node: 8
  steps_per_eval: 50
  max_token_length: 2048
  eval_handling: STOP_TRAIN
  eval_limit_ratio: 0.1
  inference_weight: 1.0
  batch_size: 8
  max_batches_offpolicy: 3
  tokenizer_name: onster1234/grpo-chess-checkpoint-20
  use_wandb: true
  rollout_server_url: http://localhost:8000
  total_steps: 100
  wandb_name: chess_puzzle_solving_env
  num_rollouts_to_keep: 32
  num_rollouts_per_group_for_logging: -1
  ensure_scores_are_not_same: true
  data_path_to_save_groups: chess_env/rollouts/chess_env_rollout_groups.jsonl
  data_dir_to_save_evals: chess_env/chess_env_eval_results
  min_items_sent_before_logging: 2
  include_messages: false
  min_batch_allocation: null
  worker_timeout: 600.0
  thinking_mode: false
  reasoning_effort: null
  max_reasoning_tokens: null
  custom_thinking_prompt: null
  stockfish_depth: 18
  engine_time_limit: 0.1
  reward_scaling_factor: 250.0
  stockfish_path: none
  max_concurrent_evals: 4
  invalid_move_notation_reward: 0.01
  illegal_move_reward: 0.05
  format_fail_reward: 0.0
  length_penalty_coefficient: 0.2
  training_rollout_temperature: 1.0
  eval_rollout_temperature: 0.0
  train_dataset_config:
    dataset_name: codingmonster1234/chess-puzzles-rlvr
    split: train
    max_items: 5000
    curriculum_type: rating
    schedule_config:
      min_rating: 400
      max_rating: 3300
      start_rating: 500
      schedule_type: fixed_linear
      total_curriculum_step: 100
      difficulty_step: 50
      root_degree: 2
      difficulty_levels: null
      max_steps: null
      enable_infinite_loop: true
    n_bins: 5
    temperature: 1.0
    ema_alpha: 0.3
    performance_strategy: competence_based
    rebin_interval: 10
  validation_dataset_config:
    dataset_name: codingmonster1234/chess-puzzles-rlvr
    split: validation
    min_rating: 400
    max_rating: 3300
    max_items: 100
  train_dataset_checkpoint_path: null
openai:
- timeout: 1200
  num_max_requests_at_once: 512
  num_requests_for_eval: 256
  model_name: ingmonster1234/grpo
  rolling_buffer_length: 1000
  server_type: vllm
  tokenizer_name: chess-checkpoint-20
  api_key: x
  base_url: http://localhost:9001/v1
  n_kwarg_is_ignored: false
  health_check: true
slurm: false
testing: false
