env:
  group_size: 8
  max_num_workers: 4
  max_eval_workers: 16
  max_num_workers_per_node: 8
  steps_per_eval: 100
  max_token_length: 2048
  eval_handling: STOP_TRAIN
  eval_limit_ratio: 0.1
  inference_weight: 1.0
  batch_size: 8
  max_batches_offpolicy: 3
  tokenizer_name: codingmonster1234/chess-sft-modelv2
  use_wandb: true
  rollout_server_url: http://localhost:8000
  total_steps: 300
  wandb_name: chess_puzzle_solving_env
  num_rollouts_to_keep: 32
  num_rollouts_per_group_for_logging: -1
  ensure_scores_are_not_same: true
  data_path_to_save_groups: chess_env/rollouts/chess_env_rollout_groups.jsonl
  data_dir_to_save_evals: chess_env_eval_results
  min_items_sent_before_logging: 2
  include_messages: false
  min_batch_allocation: null
  worker_timeout: 600.0
  thinking_mode: false
  reasoning_effort: null
  max_reasoning_tokens: null
  custom_thinking_prompt: null
  stockfish_depth: 18
  engine_time_limit: 0.1
  reward_scaling_factor: 250.0
  stockfish_path: chess_env/stockfish/stockfish-macos-m1-apple-silicon
  max_concurrent_evals: 4
  invalid_move_notation_reward: 0.01
  illegal_move_reward: 0.05
  format_fail_reward: 0.0
  length_penalty_coefficient: 0.2
  training_rollout_temperature: 1.0
  eval_rollout_temperature: 0.0
  train_dataset_config:
    dataset_name: codingmonster1234/chess-puzzles-rlvr
    split: train
    use_curriculum: true
    bucket_size: 100
    min_rating: 400
    max_rating: 3300
    start_bucket: bucket:400-500
    curr_bucket_lookup_prob: 0.85
    dataset_percent_to_use: 0.001
    use_infinite_looping: true
  validation_dataset_config:
    dataset_name: codingmonster1234/chess-puzzles-rlvr
    split: validation
    use_curriculum: false
    bucket_size: 100
    min_rating: 400
    max_rating: 3300
    start_bucket: bucket:400-500
    curr_bucket_lookup_prob: 0.8
    dataset_percent_to_use: 0.0002
    use_infinite_looping: false
  train_dataset_checkpoint_path: null
  validation_dataset_checkpoint_path: null
openai:
- timeout: 1200
  num_max_requests_at_once: 512
  num_requests_for_eval: 256
  model_name: codingmonster1234/chess-sft-modelv2
  rolling_buffer_length: 1000
  server_type: vllm
  tokenizer_name: codingmonster1234/chess-sft-modelv2
  api_key: x
  base_url: http://localhost:8001/v1
  n_kwarg_is_ignored: false
  health_check: true
slurm: false
testing: false
